### PR TITLE
thinking-in-react-step-4-5

### PR DESCRIPTION
**Pull request by nafistiham**

### CODE REVIEW

**Comment by nafistiham** [comment]
This PR is now ready for review. @moshfiqrony vai

**Review by moshfiqrony — APPROVED** [review]
LGTM

**Review by nomandhoni-cs — APPROVED** [review]
Congratulations, @nafistiham Bhai! Hats off, Your translation is excellent and deserves recognition.

**Comment by nafistiham** [comment]
Thanks a lot 🥳🥳

**Pull request merged**
