### PR TITLE
Extracting state logic into a reducer (100% finished)

### PR DESCRIPTION
**Pull request by HabibMollah**

### CODE REVIEW

**Comment by HabibMollah** [comment]
পেজ পুরোটা অনুবাদ শেষ হলো

**Comment by HabibMollah** [comment]
@nafistiham @moshfiqrony bhai, awaiting your review. Check it out when you get some free time 😊.
I have plans to start working on another page from the next week, It would be awesome if this gets merged before that.

**Comment by moshfiqrony** [comment]
> @nafistiham @moshfiqrony bhai, awaiting your review. Check it out when you get some free time 😊. I have plans to start working on another page from the next week, It would be awesome if this gets merged before that.

on it

**Review by moshfiqrony — APPROVED** [review]
LGTM

**Pull request merged**
